export const Zones = [
    "Orange Zone (13-15, 17)",
    "Yellow Zone (10-12, 16)",
    "Blue Zone (8, 9, 30, 31)",
    "Purple Zone (5b, 6a/b, 7)",
    "Charge",
    "TL",
    "Breaker",
    "Lion 3 Resource (Orange/Yellow)",
    "Lion 4 Resource (Red/Silver/Pink)",
    "Blue Zone (30, 31)",
    "Pink Zone (26, 27, 28, 29)",
    "Silver Zone (22-25)",
    "Lion 2 Resource (Purple/Blue)",
    "Discharge Lounge",
    "Zebra Resource",
    "Purple Zone 5b",
    "Zebra 2 (3b - 5a)",
    "Zebra 1 (1a - 3a)",
    "Screener",
    "Triage 1",
    "Sedation/Triage 2",
    "Red Zone (18-21)",
    "Trauma (1)",
    "Trauma (2 a/b)",
    "Silver Zone (22)",
    "Supertrack Cheetah"

]